POST http://localhost:3084 HTTP/1.1
content-type: application/json

{
    "kind": "depotLoad",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6Imp3dCJ9.eyJhZGRpdGlvbmFsIjp7ImFjY2Vzc0xldmVsIjoiZWRpdCJ9LCJpc3MiOiJtc3NxbHRhc2stYXBwIiwiaWF0IjoxNjQ0MTQ5Njk0ODg0LCJleHAiOjE2NDQyMzYwOTQ4ODR9.Q5UkhcL40YYEuKuWI1lHTDEFwCJ3HztTULkcECNu8FA="
}