POST http://localhost:3084 HTTP/1.1
content-type: application/json

{
    "kind": "historyServiceList",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6Imp3dCJ9.eyJhZGRpdGlvbmFsIjp7ImFjY2Vzc0xldmVsIjoiZWRpdCJ9LCJpc3MiOiJtc3NxbHRhc2stYXBwIiwiaWF0IjoxNjQzMjg5NzcwMDExLCJleHAiOjE2NDMzNzYxNzAwMTF9.uTIpl0vmmPllfKvvdoPvoZq0xamBJDmXMozL7oSZbLM=",
    "d1": "20200101",
    "d2": "20250101"
}