POST http://localhost:3000 HTTP/1.1
content-type: application/json

{
    "kind": "historyServiceItemDownload",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6Imp3dCJ9.eyJhZGRpdGlvbmFsIjp7ImFjY2Vzc0xldmVsIjoiZWRpdCJ9LCJpc3MiOiJtc3NxbHRhc2stYXBwIiwiaWF0IjoxNjQzMTAxOTM2NDk5LCJleHAiOjE2NDMxODgzMzY0OTl9.eV0PIZ6l8JtYhz+y/RDfH7fz1vUs1+Mcrqo07EwC1o8=",
    "file": "debug_20211222.txt"
}