POST http://localhost:3084 HTTP/1.1
content-type: application/json

{
    "kind": "historyTaskDay",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6Imp3dCJ9.eyJhZGRpdGlvbmFsIjp7ImFjY2Vzc0xldmVsIjoiZWRpdCJ9LCJpc3MiOiJtc3NxbHRhc2stYXBwIiwiaWF0IjoxNjQzNDUxNzU3NDcwLCJleHAiOjE2NDM1MzgxNTc0NzB9.o9e7UzO1/IDwL+pcVHB+vkmLRLQGhONwiaYMeL1+nCk=",
    "d": "20211221",
    "task": "task3"
}